enum ActionsEnums {
    ERROR_SET_ERROR = 'error/SET_ERROR',
    ERROR_SET_WARNING = 'error/SET_WARNING',
    SET_SUCCESS = 'SET_SUCCESS',

    LOADING = 'Loading',
    SAVING = 'Saving',
    PROCESSING = 'Processing',

    GET_TOKEN = 'GET_TOKEN',
    GET_CLASSROOM_LIST = 'GET_CLASSROOM_LIST',
    GET_OWNED_CLASSROOM_LIST = 'GET_OWNED_CLASSROOM_LIST',
    GET_ARCHIVED_CLASSROOM_LIST = 'GET_ARCHIVED_CLASSROOM_LIST',
    GET_MEMBERS_LIST = 'GET_MEMBERS_LIST',
    GET_POSTS_LIST = 'GET_POSTS_LIST',
    GET_ASSIGNMENTS_LIST = 'GET_ASSIGNMENTS_LIST',
    GET_SUBMISSIONS_LIST = 'GET_SUBMISSIONS_LIST',

    GET_ASSIGNMENTS_COMMENTS_LIST = 'GET_ASSIGNMENTS_COMMENTS_LIST',
    GET_POST_COMMENTS_LIST = 'GET_POST_COMMENTS_LIST',
    GET_SUBMISSION_COMMENTS_LIST = 'GET_SUBMISSION_COMMENTS_LIST'
}

export default ActionsEnums;
