enum ActionsEnums {
    ERROR_SET_ERROR = 'error/SET_ERROR',
    ERROR_SET_WARNING = 'error/SET_WARNING',
    SET_SUCCESS = 'SET_SUCCESS',

    LOADING = 'Loading',
    SAVING = 'Saving',
    PROCESSING = 'Processing',

    GET_TOKEN = 'GET_TOKEN',
    GET_CLASSROOM_LIST = 'GET_CLASSROOM_LIST',
    GET_MEMBERS_LIST = 'GET_MEMBERS_LIST',
    GET_POSTS_LIST = 'GET_POSTS_LIST',
    GET_ASSIGMENTS_LIST = 'GET_ASSIGMENTS_LIST',
    GET_SUBMISSIONS_LIST = 'GET_SUBMISSIONS_LIST'
}

export default ActionsEnums;
